swagger: "2.0"
#openapi: 3.0.0
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article

consumes:
  - application/json
produces:
  - application/json
basePath: /api

paths:
  /todo:
    get:
      operationId: views.get_todo_items
      tags:
        - Todo
      summary: Get Todo objects
      description: Get list of todo or single one
      responses:
        200:
          description: Get Items
          schema:
            type: array
            items:
              properties:
                id:
                  type: integer
                text:
                  type: string
                completed:
                  type: boolean

    post:
      tags:
        - Todo
      operationId: views.create_todo
      summary: Create Todo objects
      parameters:
        - name: todo
          in: body
          description: Todo to create
          required: True
          schema:
            type: object
            properties:
              text:
                type: string
              completed:
                type: boolean
      responses:
        201:
          description: Created

