"""empty message

Revision ID: afe06b7994ea
Revises: 7887b04c3246
Create Date: 2022-02-28 00:20:32.376196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe06b7994ea'
down_revision = '7887b04c3246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_list', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todo_list', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo_list', type_='foreignkey')
    op.drop_column('todo_list', 'user_id')
    # ### end Alembic commands ###
