"""empty message

Revision ID: fc2090de04de
Revises: 
Create Date: 2022-02-22 23:12:05.172524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc2090de04de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todo', sa.Column('todo_list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todo', 'todo_list', ['todo_list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column('todo', 'todo_list_id')
    op.drop_table('todo_list')
    # ### end Alembic commands ###
